import { z } from 'zod';
import { isoDateTimeSchema, paginationQuerySchema, uuidSchema } from './common';

export const auditLogsQuerySchema = paginationQuerySchema
  .extend({
    entityType: z.string().trim().max(60).optional(),
    entityId: uuidSchema.optional(),
    actorUserId: uuidSchema.optional(),
    action: z.string().trim().max(60).optional(),
    from: isoDateTimeSchema.optional(),
    to: isoDateTimeSchema.optional(),
  })
  .strict();
export type AuditLogsQuery = z.infer<typeof auditLogsQuerySchema>;

/** שמות הפעולות שנשמרות ב-Audit Log (§7.16). */
export const AuditAction = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_STARTED: 'TASK_STARTED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_CANCELLED: 'TASK_CANCELLED',
  PACKAGE_CREATED: 'PACKAGE_CREATED',
  PACKAGE_UPDATED: 'PACKAGE_UPDATED',
  PACKAGE_CONTENT_ADDED: 'PACKAGE_CONTENT_ADDED',
  PACKAGE_CONTENT_REMOVED: 'PACKAGE_CONTENT_REMOVED',
  PACKAGE_CONTENT_UPDATED: 'PACKAGE_CONTENT_UPDATED',
  PACKAGE_SEALED: 'PACKAGE_SEALED',
  PACKAGE_REOPENED: 'PACKAGE_REOPENED',
  PACKAGE_LABEL_PRINTED: 'PACKAGE_LABEL_PRINTED',
  PACKAGE_SCANNED: 'PACKAGE_SCANNED',
  PACKAGE_RECEIVED: 'PACKAGE_RECEIVED',
  PACKAGE_DELIVERED: 'PACKAGE_DELIVERED',
  MISSION_CREATED: 'MISSION_CREATED',
  MISSION_UPDATED: 'MISSION_UPDATED',
  MISSION_ROUTE_CHANGED: 'MISSION_ROUTE_CHANGED',
  MISSION_PACKAGES_ADDED: 'MISSION_PACKAGES_ADDED',
  MISSION_PACKAGE_REMOVED: 'MISSION_PACKAGE_REMOVED',
  MISSION_LOADING_STARTED: 'MISSION_LOADING_STARTED',
  MISSION_STOP_ARRIVED: 'MISSION_STOP_ARRIVED',
  MISSION_PACKAGE_LOADED: 'MISSION_PACKAGE_LOADED',
  MISSION_DEPARTED: 'MISSION_DEPARTED',
  MISSION_UNLOADING_STARTED: 'MISSION_UNLOADING_STARTED',
  MISSION_PACKAGE_UNLOADED: 'MISSION_PACKAGE_UNLOADED',
  MISSION_COMPLETED: 'MISSION_COMPLETED',
  MISSION_CANCELLED: 'MISSION_CANCELLED',
  JOIN_REQUEST_CREATED: 'JOIN_REQUEST_CREATED',
  JOIN_REQUEST_APPROVED: 'JOIN_REQUEST_APPROVED',
  JOIN_REQUEST_REJECTED: 'JOIN_REQUEST_REJECTED',
  AUTHORIZATION_DENIED: 'AUTHORIZATION_DENIED',
} as const;
export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

export const AUDIT_ACTION_LABEL: Record<AuditAction, string> = {
  LOGIN_SUCCESS: 'התחברות',
  LOGIN_FAILED: 'ניסיון התחברות שנכשל',
  LOGOUT: 'התנתקות',
  TOKEN_REFRESHED: 'חידוש חיבור',
  TASK_CREATED: 'יצירת משימת אריזה',
  TASK_UPDATED: 'עדכון משימה',
  TASK_STARTED: 'התחלת משימה',
  TASK_COMPLETED: 'השלמת משימה',
  TASK_CANCELLED: 'ביטול משימה',
  PACKAGE_CREATED: 'יצירת אריזה',
  PACKAGE_UPDATED: 'עדכון אריזה',
  PACKAGE_CONTENT_ADDED: 'הוספת תכולה',
  PACKAGE_CONTENT_REMOVED: 'הסרת תכולה',
  PACKAGE_CONTENT_UPDATED: 'עדכון תכולה',
  PACKAGE_SEALED: 'סגירת אריזה',
  PACKAGE_REOPENED: 'פתיחת אריזה מחדש',
  PACKAGE_LABEL_PRINTED: 'הדפסת תווית',
  PACKAGE_SCANNED: 'סריקת אריזה',
  PACKAGE_RECEIVED: 'קליטת אריזה',
  PACKAGE_DELIVERED: 'פיזור אריזה לחדר',
  MISSION_CREATED: 'יצירת שליחות',
  MISSION_UPDATED: 'עדכון שליחות',
  MISSION_ROUTE_CHANGED: 'שינוי מסלול',
  MISSION_PACKAGES_ADDED: 'הוספת אריזות לשליחות',
  MISSION_PACKAGE_REMOVED: 'הסרת אריזה משליחות',
  MISSION_LOADING_STARTED: 'תחילת העמסה',
  MISSION_STOP_ARRIVED: 'הגעה לעצירה',
  MISSION_PACKAGE_LOADED: 'העמסת אריזה',
  MISSION_DEPARTED: 'יציאה לדרך',
  MISSION_UNLOADING_STARTED: 'תחילת פריקה',
  MISSION_PACKAGE_UNLOADED: 'פריקת אריזה',
  MISSION_COMPLETED: 'סיום שליחות',
  MISSION_CANCELLED: 'ביטול שליחות',
  JOIN_REQUEST_CREATED: 'בקשת הצטרפות לשליחות',
  JOIN_REQUEST_APPROVED: 'אישור בקשת הצטרפות',
  JOIN_REQUEST_REJECTED: 'דחיית בקשת הצטרפות',
  AUTHORIZATION_DENIED: 'ניסיון גישה לא מורשה',
};
